title: "DraCor Textbook"
author: "DraCorOS Team"
copyright: "2026"
only_build_toc_files: true

repository:
  url: https://github.com/dracor-org/dracor-textbook
  path_to_book: docs
  branch: main

html:
  use_repository_button: true
  use_issues_button: true

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
  config:
    bibtex_bibfiles:
      - references.bib
  config:
    html_logo: _static/figures/logo.png
    html_favicon: _static/figures/favicon.png
    bibtex_bibfiles:
      - references.bib
    html_theme_options:
      extra_footer: |
        <p>This work is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. To view a copy of this licence, visit <a href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a>.</p>
        <p>This OER was created as part of "Fostering Open Science in Digital Humanities by connecting the 'DraCor' Ecosystem to EOSC" Project.</p> 
        <p>The project was funded by <a href="https://oscars-project.eu/projects/dracoros-fostering-open-science-digital-humanities-connecting-dracor-ecosystem-eosc" target="_blank" class="external-link">OSCARS</a>.</p>
        
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - linkify
    - substitution

# Execute only assessment pages (chapters are excluded from execution).
# Jupyter Book config reference: https://jupyter-book.readthedocs.io/v1/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - "chapters/*"