title: "DraCor Textbook"
author: "DraCorOS Team"
copyright: "2026"
only_build_toc_files: true

repository:
  url: https://github.com/dracor-org/dracor-textbook
  path_to_book: docs
  branch: main

html:
  use_repository_button: true
  use_issues_button: true

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
  config:
    bibtex_bibfiles:
      - references.bib
  config:
    html_logo: _static/figures/logo.png
    html_favicon: _static/figures/favicon.png
    bibtex_bibfiles:
      - references.bib
    html_theme_options:
      extra_footer: |
        <p>The DraCor Textbook has benefited from “DraCorOS. Fostering Open Science in Digital Humanities”.</p> 
        <p>We acknowledge the OSCARS project, which has received funding from the European Commission’s Horizon Europe Research and Innovation programme under grant agreement Nº. 101129751.</p>
        <p>This work is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. To view a copy of this licence, visit <a href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a>.</p>
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - linkify
    - substitution

# Execute only assessment pages (chapters are excluded from execution).
execute:
  execute_notebooks: force
  timeout: 120
  allow_errors: false
  exclude_patterns:
    - "chapters/*"